
# apiVersion - Kubernetes API version
# kind - the type of object you want to create
# metadata - info about the object so that it can be uniquely identified
# spec - desired state of the object
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-redis
  labels:
    app: flask-redis
spec:
  selector:
    matchLabels:
      app: flask-redis
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-redis
    spec:
      containers:
      - name: flask-redis
        image: moditamam/flask-redis-1110:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
