
# apiVersion - Kubernetes API version
# kind - the type of object you want to create
# metadata - info about the object so that it can be uniquely identified
# spec - desired state of the object
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-redis
  labels:
    app: flask-redis
spec:
  selector:
    matchLabels:
      app: flask-redis
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-redis
    spec:
      containers:
      - name: flask-redis
        image: moditamam/flask-redis-1110:latest
        imagePullPolicy: Always
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        - containerPort: 5000
